// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hflfnvemuqilsvanyyqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbGZudmVtdXFpbHN2YW55eXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTM2NjEsImV4cCI6MjA2NzY4OTY2MX0.D8MQAK19McrTL4cPTIhe1KfS8yAk8htKRiNlAZ-a4PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});